export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SAVE_PATTERN = 'SAVE_PATTERN';
export const CALCULATE_PATTERN = 'CALCULATE_PATTERN';

